TestDataXLSX = \\src\\main\\resources\\dataPool\\TestData.xlsx
TestReport = \\src\\main\\resources\\reports
ResourcesPath = \\src\\main\\resources\\

QAURL=
QAUID=
QAPAS=

DEVURL= https://tutorialsninja.com/demo/
DEVUID=vijender.r@inheritx.com
DEVPAS=V80..63@45k

PRODURL=
PRODUID=
PRODPAS=

OTHERURL=
OTHERUID=
OTHERPAS=

waitTimeout=30

selGrid=false
headLessFlag=false

CustomProxyRequired=false

API_Url = https://api.restful-api.dev/objects
extentReportFlag = true

AWSAccessKey=
AWSSecretKey=
